import DashNav from "@/components/DashNav/DashNav";
import "../globals.css";
export const metadata = {
  title: "MeetReady || Dashboard",
  description: "Generated by Tech Army",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className="flex justify-between bg-purple-100 ">
        <DashNav />
        <div className="max-w-7xl mx-auto min-h-screen">{children}</div>
      </body>
    </html>
  );
}
