
import './globals.css'
import Navber from '@/components/Navber/Navber'
import LeftSideBer from '@/components/LeftSideBer/LeftSideBer'
import Container from '@/components/container/Container'
import Footer from '@/components/Footer/Footer'



export const metadata = {
  title: 'MeetReady',
  description: 'Generated by Tech Army',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className='flex flex-col bg-purple-100'>
          <Navber />
          <div className='flex flex-row'>
            <LeftSideBer />
            <Container>{children}</Container>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  )
}
